## Created by pc at 4/24/2018
#
#Feature: Add bundle order
#
#  Scenario: successful add order raft o bargasht for client
#    Given login with username 09022012056 and password as1234
#    When  Add order for raft o bargasht with options like the following:
#      | weight | price  | source_city | destination_city  | source_region_id | destination_region_id | load_type | vehicle_type | vehicle_options | suspention_type | load_value | description  | sender_name | sender_phone | sender_company | receiver_name | receiver_phone | receiver_company | package_options | length | width | height | baarnameh | baarnameh_options | unload_option | sender_mobile_phone | announce_type | payment_type | surplus_costs | source_address      | destination_address        | receiver_mobile_phone |
#      | 5      | 150000 | تهران       | ساری             | 22               | 16                    | ابمیوه    | joft         | joft:hichkodam  |                 | 10000000   | هیچی         | عسل عیار    | 09552020202  | سانا           | نوید          | 09552020202    | سانا             | karton          | 1      | 1     | 1      | yes       |                   | day           | 09552020202         | ubaar         | sender       | 200000        | خیابان اول کوچه دوم | خیابان دوم کوچه سوم        | 09552020202           |
#      | 2.5    | 100000 | ساری        | تهران            | 16               | 22                    | نخود      | joft         | joft:hichkodam  |                 | 50000000   |              | محمد رضایی  | 09630213633  | سانا گستر      | وحید افشاری   | 09630213633    | Sana             | falleh          |        |       |        | yes       |                   | day           | 09552020202         | ubaar         | sender       | 100000        |                     | خیابان دوم کوچه سوم پلاک 8 |                       |
#      | 6      | 200000 | تهران       | اصفهان           | 22               | 3                     | میوه      | joft         | joft:hichkodam  |                 | 100000000  | تخلیه ساعت 2 | رضا بینا    | 09552020202  | سانا گستر سبز  | عباس ثابتی    | 09852222222    | سبز              | bandil          |        |       |        | no        | havaleh           | day           | 09552020202         | ubaar         | receiver     | 100000        |                     |                            |                       |
#      | 10     | 142500 | اصفهان      | تهران            | 3                | 22                    | اهن       | joft         | joft:hichkodam  | fanari          | 23000000   |              | علیرضا نوری | 09658745222  | اوبار          |               | 09552020202    |                  | kiseh_gooni     | 1.5    | 2.25  | 2      | yes       |                   | night         | 09552020202         | ubaar         | sender       | 100000        |                     |                            |                       |
#      | 5      | 785300 | کرمان       | تهران            | 21               | 22                    | پروفیل    | joft         | joft:hichkodam  | baloni          | 70000000   |              |             |              |                |               |                |                  | hichkodam       | 1      | 2     | 2      | no        | hichkodam         | night         |                     | ubaar         | receiver     | 100000        |                     |                            |                       |
#      | 6      | 200000 | تهران       | کرمان            | 22               | 21                    | میوه      | joft         | joft:hichkodam  |                 | 100000000  | تخلیه ساعت 2 | رضا بینا    | 09552020202  | سانا گستر سبز  | عباس ثابتی    | 09852222222    | سبز              | bandil          |        |       |        | no        | havaleh           | day           | 09552020202         | ubaar         | receiver     | 100000        |                     |                            |                       |
#      | 6      | 500000 | مشهد        | تهران            | 34               | 22                    | چوب       | joft         | joft:hichkodam  |                 | 100000000  | تخلیه ساعت 2 | رضا بینا    | 09552020202  | سانا گستر سبز  | عباس ثابتی    | 09852222222    | سبز              | bandil          |        |       |        | no        | havaleh           | day           | 09552020202         | ubaar         | receiver     | 100000        |                     |                            |                       |
#      | 6      | 140000 | تهران       | مشهد             | 22               | 34                    | اهن       | joft         | joft:hichkodam  |                 | 100000000  | تخلیه ساعت 2 | رضا بینا    | 09552020202  | سانا گستر سبز  | عباس ثابتی    | 09852222222    | سبز              | bandil          |        |       |        | no        | havaleh           | day           | 09552020202         | ubaar         | receiver     | 100000        |                     |                            |                       |
#
#    Then Success flag for raft o bargasht order is 1
#    And status is 200
#
#
##